"""add is_active to doctors

Revision ID: 5991c2527af5
Revises: b5beab63df15
Create Date: 2026-05-17 14:32:48.351908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5991c2527af5'
down_revision: Union[str, Sequence[str], None] = 'b5beab63df15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'is_active')
    # ### end Alembic commands ###
