"""add medical fields to appointments

Revision ID: b5beab63df15
Revises: e1e90d92c8a2
Create Date: 2026-05-07 23:20:37.559477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5beab63df15'
down_revision: Union[str, Sequence[str], None] = 'e1e90d92c8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('anamnesis', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('diagnosis', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('treatment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'treatment')
    op.drop_column('appointments', 'diagnosis')
    op.drop_column('appointments', 'anamnesis')
    # ### end Alembic commands ###
